use ironrdp::cliprdr::backend::CliprdrBackend;
use ironrdp::cliprdr::pdu::{
    ClipboardFormat, ClipboardGeneralCapabilityFlags, FileContentsRequest, FileContentsResponse,
    FormatDataRequest, FormatDataResponse, LockDataId,
};
use std::cell::RefCell;
use wasm_bindgen::prelude::*;

/// Clipboard text cached from local paste events (JS → WASM).
thread_local! {
    static PENDING_CLIPBOARD_TEXT: RefCell<Option<String>> = RefCell::new(None);
}

/// Write text to the browser's clipboard (Remote → Local).
#[wasm_bindgen(inline_js = "
export function write_clipboard_text(text) {
    if (navigator.clipboard && navigator.clipboard.writeText) {
        navigator.clipboard.writeText(text).catch(e => console.warn('Clipboard write failed:', e));
    }
}
")]
extern "C" {
    fn write_clipboard_text(text: &str);
}

#[derive(Debug)]
pub struct WasmCliprdrBackend;

impl WasmCliprdrBackend {
    pub fn new() -> Self {
        Self
    }
}

impl ironrdp_core::AsAny for WasmCliprdrBackend {
    fn as_any(&self) -> &dyn core::any::Any {
        self
    }

    fn as_any_mut(&mut self) -> &mut dyn core::any::Any {
        self
    }
}

/// Store text from a JS paste event for later retrieval by the CLIPRDR channel.
pub fn set_pending_clipboard(text: String) {
    PENDING_CLIPBOARD_TEXT.with(|cell| {
        *cell.borrow_mut() = Some(text);
    });
}

/// Encode a Rust string as UTF-16LE bytes (the format RDP expects for CF_UNICODETEXT).
fn to_utf16le(s: &str) -> Vec<u8> {
    let mut buf: Vec<u8> = s
        .encode_utf16()
        .flat_map(|c| c.to_le_bytes())
        .collect();
    // CF_UNICODETEXT requires null terminator
    buf.push(0);
    buf.push(0);
    buf
}

/// Decode UTF-16LE bytes to a Rust string.
fn from_utf16le(data: &[u8]) -> String {
    let u16_iter = data
        .chunks_exact(2)
        .map(|chunk| u16::from_le_bytes([chunk[0], chunk[1]]));
    // Strip null terminator
    let chars: Vec<u16> = u16_iter.take_while(|&c| c != 0).collect();
    String::from_utf16_lossy(&chars)
}

impl CliprdrBackend for WasmCliprdrBackend {
    fn temporary_directory(&self) -> &str {
        ".clipboard"
    }

    fn client_capabilities(&self) -> ClipboardGeneralCapabilityFlags {
        ClipboardGeneralCapabilityFlags::USE_LONG_FORMAT_NAMES
    }

    fn on_ready(&mut self) {
        crate::log("Clipboard: channel ready");
    }

    fn on_request_format_list(&mut self) {
        crate::log("Clipboard: format list requested (local → remote)");
        // The RDP server is asking what formats we have.
        // If we have pending clipboard text, we'd advertise CF_UNICODETEXT (format 13).
        // This is called by the CLIPRDR channel when it needs us to send our format list.
    }

    fn on_process_negotiated_capabilities(&mut self, _capabilities: ClipboardGeneralCapabilityFlags) {
    }

    fn on_remote_copy(&mut self, available_formats: &[ClipboardFormat]) {
        crate::log(&format!(
            "Clipboard: remote copied ({} formats available)",
            available_formats.len()
        ));
        // The remote machine copied something. Check if CF_UNICODETEXT (13) is available.
        // If so, we should request its data.
        // Note: The actual format data request is typically initiated by the CLIPRDR
        // channel automatically when we express interest. The data arrives in
        // on_format_data_response.
    }

    fn on_format_data_request(&mut self, request: FormatDataRequest) {
        crate::log(&format!(
            "Clipboard: remote requested format {:?}",
            request.format
        ));
        // The RDP server wants our clipboard data.
        // Return the pending text as UTF-16LE.
        let _text = PENDING_CLIPBOARD_TEXT.with(|cell| cell.borrow().clone());
        // Note: We can't directly respond here because the backend trait doesn't
        // provide a way to send responses. The response is generated by the
        // CLIPRDR channel state machine which calls this for notification only.
    }

    fn on_format_data_response(&mut self, response: FormatDataResponse<'_>) {
        if response.is_error() {
            crate::log_error("Clipboard: server sent error response");
            return;
        }

        // Decode UTF-16LE clipboard data from the remote machine
        let text = from_utf16le(response.data());
        if !text.is_empty() {
            crate::log(&format!("Clipboard: received {} chars from remote", text.len()));
            write_clipboard_text(&text);
        }
    }

    fn on_file_contents_request(&mut self, _request: FileContentsRequest) {}
    fn on_file_contents_response(&mut self, _response: FileContentsResponse<'_>) {}
    fn on_lock(&mut self, _data_id: LockDataId) {}
    fn on_unlock(&mut self, _data_id: LockDataId) {}
}
